// flow-typed signature: 682d10d44ad6a096cfe4c134c720e570
// flow-typed version: <<STUB>>/koa-webpack-hot-middleware_v^1.0.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-webpack-hot-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-webpack-hot-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-webpack-hot-middleware/index' {
  declare module.exports: $Exports<'koa-webpack-hot-middleware'>;
}
declare module 'koa-webpack-hot-middleware/index.js' {
  declare module.exports: $Exports<'koa-webpack-hot-middleware'>;
}
