// flow-typed signature: d679c4e8684d0b277bc01732194f93e3
// flow-typed version: <<STUB>>/koa-static-server_v^1.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-static-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-static-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-static-server/index' {
  declare module.exports: $Exports<'koa-static-server'>;
}
declare module 'koa-static-server/index.js' {
  declare module.exports: $Exports<'koa-static-server'>;
}
