// flow-typed signature: a4dc4e8d927186adfc3a6105301443d1
// flow-typed version: <<STUB>>/koa-webpack-dev-middleware_v^1.4.5/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-webpack-dev-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-webpack-dev-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-webpack-dev-middleware/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-webpack-dev-middleware/lib/index.js' {
  declare module.exports: $Exports<'koa-webpack-dev-middleware/lib/index'>;
}
